model: "FNO"
modes: 12
ds: 2
output_features: 1
dataset: "2dturb"
data_path: "/content/drive/MyDrive/2d_NS/Re100"
batch_size: 4
max_epochs: 50
time_window: 10
save_path: './'
push_forward: True
teacher_forcing: True
tpu: False
input_steps: 1
unroll_steps: 4
checkpoint: False
train_loss: False
unroll_loss: False
lr: 0.0005222450594198889
x_data: 1.4837521202862263
x_adv: 50.47508021816611
x_diff: 3.037538845092058
x_dt: 35.43678056448698
x_stab: 59.673507045954466
pf_steps: 4