model: "FNO"
modes: 32
ds: 2
output_features: 1
dataset: "2dturb"
data_path: "/mnt/2d_NS/NS_L2pi_256_T200_Re100"
batch_size: 16
max_epochs: 50
time_window: 10
save_path: '/mnt/FNO_Re100_causal'
push_forward: False
teacher_forcing: False
tpu: False
input_steps: 1
unroll_steps: 4
checkpoint: False
train_loss: False
unroll_loss: False
x_data: 1.0
x_adv: 10.0
x_diff: 10.0
x_dt: 10.0
x_stab: 0.0
x_eq: 10.0
lr: 0.001
pf_steps: 3
id: False
causality_train: True
epsilon_data: 0.01
epsilon_eq: 0.01