model: "FNO"
modes: 12
ds: 2
output_features: 1
dataset: "2dturb"
data_path: "/mnt/2d_NS/NS_L2pi_256_T200_Re100"
batch_size: 16
max_epochs: 20
time_window: 10
save_path: '/mnt/FNO_hyperparams'
push_forward: True
teacher_forcing: True
tpu: False
input_steps: 1
unroll_steps: 4
checkpoint: False
train_loss: False
unroll_loss: False